Repository letsencrypt/website, pull requests merged in 2020-01, with the labels that each got.

#818 Some typo fixed and enhancements on semantic issues
  i18n/es.toml
Labels: i18n

#804 Fix langs
  config/_default/languages.toml
  config/_default/menu.sr.toml
  content/sr/about.md
  content/sr/become-a-sponsor.html
  content/sr/certificates.md
  content/sr/contact.md
  content/sr/docs/_index.md
  content/sr/docs/account-id.md
  content/sr/docs/acme-protocol-updates.md
  content/sr/docs/allow-port-80.md
  content/sr/docs/caa.md
  content/sr/docs/cert-compat.md
  content/sr/docs/certificates-for-localhost.md
  content/sr/docs/challenge-types.md
  content/sr/docs/client-options.md
  content/sr/docs/ct-logs.html
  content/sr/docs/expiration-emails.md
  content/sr/docs/faq.md
  content/sr/docs/glossary.md
  content/sr/docs/godaddy.md
  content/sr/docs/integration-guide.md
  content/sr/docs/rate-limits.md
  content/sr/docs/revoking.md
  content/sr/docs/staging-environment.md
  content/sr/donate.html
  content/sr/getinvolved.md
  content/sr/getting-started.md
  content/sr/how-it-works.md
  content/sr/privacy.md
  content/sr/repository.md
  content/sr/sponsors.html
  content/sr/stats-dashboard.html
  content/sr/stats.html
  content/sr/thankyou.md
  content/sr/trademarks.md
  content/sr/upcoming-features.md
  i18n/sr-sp.toml
  layouts/_default/baseof.html
  layouts/index.html
  layouts/partials/header.html
  layouts/partials/langs.html
  layouts/post/list.html
  layouts/shortcodes/i18n_status.html
  layouts/shortcodes/lastmod.html
  layouts/shortcodes/plotly.html
Labels: i18n

#809 Paypal i18n
  config/_default/languages.toml
  content/de/donate.html
  content/en/donate.html
  content/es/donate.html
  content/fr/donate.html
  content/id/donate.html
  content/ja/donate.html
  content/ko/donate.html
  content/pt-br/donate.html
  content/ru/donate.html
  content/sr/donate.html
  content/sv/donate.html
  content/zh-cn/donate.html
  content/zh-tw/donate.html
  i18n/de.toml
  i18n/en.toml
  i18n/es.toml
  i18n/fr.toml
  i18n/id.toml
  i18n/ja.toml
  i18n/ko.toml
  i18n/pt-br.toml
  i18n/ru.toml
  i18n/sr-sp.toml
  i18n/sv.toml
  i18n/zh-cn.toml
  i18n/zh-tw.toml
  layouts/shortcodes/paypal.html
Labels: i18n

#840 Update privacy.md translations
  content/es/privacy.md
  content/ko/privacy.md
  content/zh-cn/privacy.md
Labels: translation

#838 Update fr.toml
  i18n/fr.toml
Labels: translation

#837 Link to annual report in /about/ in French
  content/fr/about.md
Labels: translation

#835 Update upcoming-features in French for f2055f4 and 8a27e4c
  content/fr/upcoming-features.md
Labels: translation

#836 linkTitle for how-it-works in French
  content/fr/how-it-works.md
Labels: translation

#834 Apply #633 to translations
  content/de/contact.md
  content/fr/contact.md
  content/id/contact.md
  content/ja/contact.md
  content/ko/contact.md
Labels: translation

#833 Update translations of getinvolved for #755
  content/de/getinvolved.md
  content/es/getinvolved.md
  content/fr/getinvolved.md
  content/ja/getinvolved.md
  content/ko/getinvolved.md
  content/sr/getinvolved.md
  content/zh-tw/getinvolved.md
Labels: translation

#831 Fix lastmod for translations of /donate/
  content/de/donate.html
  content/es/donate.html
  content/fr/donate.html
  content/id/donate.html
  content/ja/donate.html
  content/pt-br/donate.html
  content/sr/donate.html
  content/zh-tw/donate.html
Labels: translation

#850 German translation for #832
  content/de/about.md
  content/de/become-a-sponsor.html
  content/de/contact.md
  content/de/docs/account-id.md
  content/de/docs/acme-protocol-updates.md
  content/de/docs/allow-port-80.md
  content/de/docs/challenge-types.md
  content/de/docs/client-options.md
  content/de/docs/ct-logs.html
  content/de/docs/faq.md
  content/de/docs/godaddy.md
  content/de/docs/integration-guide.md
  content/de/docs/rate-limits.md
  content/de/docs/staging-environment.md
  content/de/privacy.md
  i18n/de.toml
Labels: translation

#853 [ja] Update Japanese Translation
  content/ja/about.md
  content/ja/become-a-sponsor.html
  content/ja/contact.md
  content/ja/docs/ct-logs.html
  content/ja/docs/faq.md
  i18n/ja.toml
Labels: translation

#861 acmetool ACMEv2 support
  data/clients.json
Labels: client-options

#681 Update zh-tw translation
  config/_default/languages.toml
  content/zh-tw/about.md
  content/zh-tw/become-a-sponsor.html
  content/zh-tw/certificates.md
  content/zh-tw/contact.md
  content/zh-tw/docs/account-id.md
  content/zh-tw/docs/acme-protocol-updates.md
  content/zh-tw/docs/allow-port-80.md
  content/zh-tw/docs/caa.md
  content/zh-tw/docs/cert-compat.md
  content/zh-tw/docs/certificates-for-localhost.md
  content/zh-tw/docs/challenge-types.md
  content/zh-tw/docs/client-options.md
  content/zh-tw/docs/ct-logs.html
  content/zh-tw/docs/expiration-emails.md
  content/zh-tw/docs/faq.md
  content/zh-tw/docs/glossary.md
  content/zh-tw/docs/rate-limits.md
  content/zh-tw/docs/revoking.md
  content/zh-tw/docs/staging-environment.md
  content/zh-tw/donate.html
  content/zh-tw/getinvolved.md
  content/zh-tw/getting-started.md
  content/zh-tw/how-it-works.md
  content/zh-tw/sponsors.html
  content/zh-tw/stats-dashboard.html
  content/zh-tw/stats.html
  content/zh-tw/thankyou.md
  content/zh-tw/upcoming-features.md
  i18n/zh-tw.toml
Labels: translation
